[project]
name = 'quantum-resistant-digital-identity'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.institutional-verification-gateway]
path = 'contracts/institutional-verification-gateway.clar'
clarity_version = 3
epoch = 3.1

[contracts.quantum-proof-identity-vault]
path = 'contracts/quantum-proof-identity-vault.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
